---
- hosts: '{{ hosts }}'
  become: true

  tasks:
    - name: package update
      ansible.builtin.package:
        update_cache: true

    - name: Install required system packages
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      ansible.builtin.package:
        name: 
          - docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: 
          - docker
          - docker-compose

    - name: Install docker-compose Module for Python
      shell: |
        docker_compose_ver_check=$(git ls-remote https://github.com/docker/compose | grep refs/tags | grep -oE "(v?)[0-9]+\.[0-9][0-9]+\.[0-9]+$" | sort --version-sort | tail -n 1) 
        echo $docker_compose_ver_check is latest version; curl -SL https://github.com/docker/compose/releases/download/$docker_compose_ver_check/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose 
        chmod +x /usr/local/bin/docker-compose 
        echo $docker_compose_ver_check is installed
      
    - name: test
      shell: check=$(docker-compose --version) && echo $check
      register: check
    - name: Print uptime of managed node
      debug:
        msg: "{{ check }}"

    # Create Portainer Volume
    # --
    # 
    - name: Create new Volume
      community.docker.docker_volume:
        name: portainer-data
    
    # Deploy Portainer
    # --
    #   
    - name: Deploy Portainer
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        ports:
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: always


#only bash command
#docker_compose_ver_check=$(git ls-remote https://github.com/docker/compose | grep refs/tags | grep -oE "(v?)[0-9]+\.[0-9][0-9]+\.[0-9]+$" | sort --version-sort | tail -n 1); echo $docker_compose_ver_check is latest version; sudo curl -SL https://github.com/docker/compose/releases/download/$docker_compose_ver_check/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose; sudo chmod +x /usr/local/bin/docker-compose; echo $docker_compose_ver_check is installed
