---
- hosts: '{{ hosts }}'
  become: true

  tasks:
    - name: package update
      ansible.builtin.package:
        update_cache: true

    - name: Install docker dependencies
      ansible.builtin.package:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - software-properties-common
        state: latest
        update_cache: true

    - name: Add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/keyrings/docker.gpg

    - name: Add docker repository
      apt_repository:
        filename: docker 
        repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable
        state: present

    - name: Install docker engine
      ansible.builtin.package:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-scan-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
    
    - name: test
      shell: check=$(docker compose version) && echo $check
      register: check
    - name: Print uptime of managed node
      debug:
        msg: "{{ check }}"

    - name: Create Portainer Volume
      community.docker.docker_volume:
        name: portainer-data
    
    - name: Deploy Portainer
      community.docker.docker_container:
        name: portainer
        image: portainer/portainer-ce:latest
        ports:
          - "9000:9000"
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - portainer-data:/data
        restart_policy: always